export { LoginPage } from './auth/LoginPage';
export { RegisterPage } from './auth/RegisterPage';
export { ForgotPasswordPage } from './auth/ForgotPasswordPage';
export { ResetPasswordPage } from './auth/ResetPasswordPage';
export { VerifyEmailPage } from './auth/VerifyEmailPage';
export { DashboardPage } from './dashboard/DashboardPage';
export { ProfilePage } from './profile/ProfilePage';
export { NotFoundPage } from './NotFoundPage';
export { CoursesPage } from './courses/CoursesPage';
export { CourseDetailPage } from './courses/CourseDetailPage';
export { MyCoursesPage } from './courses/MyCoursesPage';
export { GradesPage } from './grades/GradesPage';
export { GradebookPage } from './grades/GradebookPage';
export { StartAttendancePage } from './attendance/StartAttendancePage';
export { GiveAttendancePage } from './attendance/GiveAttendancePage';
export { MyAttendancePage } from './attendance/MyAttendancePage';
export { AttendanceReportPage } from './attendance/AttendanceReportPage';
export { ExcuseRequestsPage } from './attendance/ExcuseRequestsPage';

